### ISSUE TITLE
Deployment fails to generate azure url

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [ballerina-platform/module-ballerinax-azure.functions#549] opened 2022-10-14 06:26 UTC
**Description:**

```ballerina
import ballerina/http;
import ballerinax/azure_functions as af;
listener af:HttpListener ep = new();
  service "hello" on ep {
      resource function 'default [string... s](@http:Payload int hoste) returns string {
          return "hello world";
      }
  }
```
code compilation and artifact generation is successful(artifact seems fine). Deployment fails to generate the url for the function.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by xlight05** [comment] 2022-10-17 09:56
Duplicate of https://github.com/ballerina-platform/module-ballerinax-azure.functions/issues/484

**Closed by xlight05** 2022-10-17 09:56 UTC
Labels: Type/Bug
