### ISSUE TITLE
Results vary when resource function is interchanged

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [ballerina-platform/module-ballerinax-azure.functions#540] opened 2022-10-11 11:06 UTC
**Description:**
```ballerina 
import ballerinax/azure_functions as af;

service / on ep1 {

    resource function get helloquery/alpha() returns string {
        return "Hello from the hello-query--";
    }

    resource function get helloquery/[string alpha]() returns string{
        return "Hello from the hello-query";
    }
}
```
Above one's results (Runtime result)differ from below one.

```ballerina 
import ballerinax/azure_functions as af;

service / on ep1 {

    resource function get helloquery/[string alpha]() returns string{
        return "Hello from the hello-query";
    }
   
    resource function get helloquery/alpha() returns string {
        return "Hello from the hello-query--";
    }
}
```
resource function with path parameter is moved to top
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by xlight05** [comment] 2022-10-20 14:25
It seems like this is the way the routing works from azure's side. If there is a path parameter that can be applied for the same path, and it followers the registered order. ;( 

Closing as this is not a bug

**Closed by xlight05** 2022-10-20 14:25 UTC
Labels: Type/Bug, Priority/High
