### ISSUE TITLE
Path parameter fails when we use rest parameter

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [ballerina-platform/module-ballerinax-azure.functions#543] opened 2022-10-12 11:39 UTC
**Description:**

$Subject (according to https://github.com/ballerina-platform/module-ballerinax-azure.functions/blob/svc-impl/spec/spec.md#233-path-parameter)

```ballerina
import ballerinax/azure_functions as af;

  service "hello" on new af:HttpListener() {
      resource function get el/[string... bar]() returns string {
          return "alph";
      }

  }

```
Following behaviour was observed.

- `curl -v https://<azure-host>/hello/el/ ` returns status code 500.(In the case of http. It is 404)
- `curl -v https://<azure-host>/hello/el/ 30` returns 404 status code.
- Generated `function.json` contains wrong route. (`hello/el`)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by xlight05** [comment] 2022-10-17 10:04
Duplicate of https://github.com/ballerina-platform/module-ballerinax-azure.functions/issues/484

**Closed by xlight05** 2022-10-17 10:04 UTC
Labels: Type/Bug
